sonar.projectKey=YOUR_PROJECT_KEY
sonar.organization=YOUR_ORGANIZATION_KEY
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11
sonar.exclusions=.venv/**,__pycache__/**,.elasticbeanstalk/**,static/**
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300